---
abstract: ~
author:
  - 'Me <loganbell@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HelloWord
no_index:
  directory:
    - inc
    - t
requires:
  Test::Most: 0
resources:
  license: http://dev.perl.org/licenses/
version: undef
